#version 450
#extension GL_GOOGLE_include_directive : require
#include "../../code/rd-vulkan/shaders/deform.glsl"
#include "../../code/rd-vulkan/shaders/specular.glsl"
layout(local_size_x = 64) in;
struct Sample { vec4 position; vec4 normal; vec4 result; vec4 eye; };
layout(set = 0, binding = 0, std430) buffer Samples { Sample samples[]; };
layout(push_constant) uniform TestPush { uint start; uint count; } pc;
void main()
{
	uint i = gl_GlobalInvocationID.x;
	if (i >= pc.count) return;
	i += pc.start;
	samples[i].result = vec4(deformPosition(samples[i].position.xyz,
		samples[i].normal.xyz, samples[i].position.w), 1.0);
	samples[i].result.w = materialSpecularAlpha(samples[i].result.xyz,
		deformNormal(samples[i].normal.xyz), samples[i].eye.xyz, deform.specularLight);
}
